const clamp = (value, min, max) => Math.min(max, Math.max(min, Number.isFinite(value) ? value : min));

/**
 * Detects two intentional forward taps. It consumes the same
 * pose sample used by the hand renderer, so a knock cannot be generated by a
 * keyboard/touch fallback or by a different hand.
 */
export class KnockGestureDetector {
  constructor({
    minVelocity = 0.52,
    minDepthDelta = 0.018,
    minScaleDelta = 0.045,
    minGrabStrength = 0.62,
    maxOpenness = 0.64,
    rearmVelocity = 0.36,
    minGapMs = 110,
    maxGapMs = 760,
    maxPairMs = 1450,
    cooldownMs = 900,
  } = {}) {
    this.minVelocity = minVelocity;
    this.minDepthDelta = minDepthDelta;
    this.minScaleDelta = minScaleDelta;
    this.minGrabStrength = minGrabStrength;
    this.maxOpenness = maxOpenness;
    this.rearmVelocity = rearmVelocity;
    this.minGapMs = minGapMs;
    this.maxGapMs = maxGapMs;
    this.maxPairMs = maxPairMs;
    this.cooldownMs = cooldownMs;
    this.reset();
  }

  reset() {
    this.lastDepth = null;
    this.lastScale = null;
    this.lastImpulseAt = null;
    this.firstImpulseAt = null;
    this.count = 0;
    this.cooldownUntil = 0;
    this.armed = true;
  }

  update(sample, { focused = false, now = performance.now() } = {}) {
    const time = Number.isFinite(now) ? now : performance.now();
    if (!focused || !sample || sample.state !== "tracked" || sample.fresh === false) {
      this.resetForFocusLoss(time);
      return false;
    }
    if (time < this.cooldownUntil) {
      this.lastDepth = this.readDepth(sample);
      this.lastScale = this.readScale(sample);
      return false;
    }

    const depth = this.readDepth(sample);
    const scale = this.readScale(sample);
    const previousDepth = this.lastDepth;
    const previousScale = this.lastScale;
    this.lastDepth = depth;
    this.lastScale = scale;
    if (!this.armed) {
      const pose = sample.gesturePose ?? sample.pose ?? sample;
      if ((Number(pose?.velocity) || 0) <= this.rearmVelocity) this.armed = true;
      return false;
    }
    if (!this.isImpulse(sample, previousDepth, depth, previousScale, scale)) return false;
    this.armed = false;

    if (this.lastImpulseAt !== null && time - this.lastImpulseAt < this.minGapMs) return false;
    if (this.firstImpulseAt !== null && time - this.firstImpulseAt > this.maxPairMs) {
      this.firstImpulseAt = null;
      this.count = 0;
    }
    if (this.firstImpulseAt === null) {
      this.firstImpulseAt = time;
      this.count = 1;
      this.lastImpulseAt = time;
      return false;
    }
    const gap = time - this.lastImpulseAt;
    if (gap > this.maxGapMs) {
      this.firstImpulseAt = time;
      this.count = 1;
      this.lastImpulseAt = time;
      return false;
    }
    this.count += 1;
    this.lastImpulseAt = time;
    if (this.count < 2) return false;
    this.cooldownUntil = time + this.cooldownMs;
    this.firstImpulseAt = null;
    this.count = 0;
    return true;
  }

  resetForFocusLoss(now = performance.now()) {
    this.lastDepth = null;
    this.lastScale = null;
    this.firstImpulseAt = null;
    this.lastImpulseAt = null;
    this.count = 0;
    if (Number.isFinite(now) && now >= this.cooldownUntil) this.cooldownUntil = 0;
  }

  readDepth(sample) {
    const pose = sample.gesturePose ?? sample.pose ?? sample;
    return Number.isFinite(pose?.depth)
      ? pose.depth
      : Number.isFinite(pose?.center?.[2]) ? pose.center[2] : null;
  }

  readScale(sample) {
    const pose = sample.gesturePose ?? sample.pose ?? sample;
    return Number.isFinite(pose?.relativeScale) ? pose.relativeScale : null;
  }

  isImpulse(sample, previousDepth, depth, previousScale, scale) {
    if (!Number.isFinite(previousDepth) || !Number.isFinite(depth)) return false;
    const pose = sample.gesturePose ?? sample.pose ?? sample;
    const velocity = Math.max(0, Number(pose?.velocity) || 0);
    const grabStrength = clamp(Number(pose?.grabStrength), 0, 1);
    const openness = clamp(Number(pose?.openness), 0, 1);
    const curls = Array.isArray(pose?.curls) ? pose.curls.map((value) => clamp(Number(value), 0, 1)) : null;
    const closedFist = grabStrength >= this.minGrabStrength && openness <= this.maxOpenness;
    // The user's natural knock pose has index/middle available for contact,
    // while ring/pinky stay folded. Allow either finger to be slightly bent.
    const twoFingerKnock = curls && curls.length >= 5
      && curls[3] >= 0.52
      && curls[4] >= 0.52
      && curls[1] <= 0.66
      && curls[2] <= 0.7
      && Math.abs(curls[1] - curls[2]) <= 0.3;
    const depthImpulse = Math.abs(depth - previousDepth) >= this.minDepthDelta;
    const scaleImpulse = Number.isFinite(previousScale) && Number.isFinite(scale)
      && Math.abs(scale - previousScale) >= this.minScaleDelta;
    return velocity >= this.minVelocity
      && (closedFist || twoFingerKnock)
      && (depthImpulse || scaleImpulse);
  }
}
